[package]
version = "0.1.0"
name = "ream-operations"
edition = "2024"

[dependencies]
# SP1 dependencies
sp1-zkvm = "5.2.1"
sp1-derive = "5.2.1"

# Ethereum dependencies
ethereum_ssz = { workspace = true }

# Ream dependencies
ream-consensus = { workspace = true }
ream-lib = { path = "../../lib" }
