[workspace]
members = ["lib", "program/operations", "script"]
resolver = "2"

[workspace.dependencies]
ethereum_ssz = "0.9"
tracing = "0.1.40"
ream-consensus = { git = "https://github.com/ReamLabs/ream", package = "ream-consensus" }

[patch.crates-io]
ethereum_hashing = { git = "https://github.com/ReamLabs/ethereum_hashing" }
