[workspace]
members = [
    "lib",
    "program",
    "script",
]
resolver = "2"

[workspace.dependencies]
tracing = "0.1.40"
ream-consensus = { git = "https://github.com/ReamLabs/ream", package = "ream-consensus" }
