[package]
version = "0.1.0"
name = "ream-operations"
edition = "2024"

[dependencies]
# SP1 dependencies
sp1-zkvm = "4.0.0"
sp1-derive = "4.0.0"

# Ethereum dependencies
ethereum_ssz = { workspace = true }

# Ream dependencies
ream-consensus = { workspace = true }
ream-lib = { path = "../lib" }
